### ISSUE TITLE
Make RandomizedRunner extensible

### ISSUE THREAD

**Issue by coderplay** [randomizedtesting/randomizedtesting#281] opened 2019-10-25 06:01 UTC
I am a Lucene and Elasticsearch developer.   Recently, we are about to add more fault injection tests to Lucene and Elasticsearch in order to enhance their fault tolerance, but due to those tests in both Lucene and Elasticsearch depend on `RandomizedRunner`, I found it's hard because  the runner class is  a final class with private methods.  I am looking forward to make it extensible.

**Comment by dweiss** [comment] 2019-10-25 06:37
Such rules are already present in Lucene in LuceneTestCase parent class -- ideally you'd write a rule (or a rule chain) and set up your test code so that it inherits from one class that prepares the environment (instead of adding those rules to the runner directly).

What are the fault tolerance rules you have in mind, by the way?

**Comment by coderplay** [comment] 2019-10-26 07:40
The idea is similar to hadoop's FI framework which is based on AspectJ. https://hadoop.apache.org/docs/r2.7.2/hadoop-project-dist/hadoop-hdfs/FaultInjectFramework.html
We can inject faults from any layer of the application. This is especially helpful for distributed system like Elasticsearch, where we can simulate some lower level issues while testing , like disk error, merge fail,  ordinals map  out of memory, etc.

Different from AspectJ which do static weaving, our idea is more towards runtime dynamic injection. Where we can simply add an annotation to the target class or method and change it behavior by injecting some errors. 

Below is an example.
https://gist.github.com/coderplay/82632cc322d4a4eb7f78e539ba4db355

**Comment by dweiss** [comment] 2019-10-28 07:59
Duplicate of discussion in GH-282

**Closed by dweiss** 2019-10-28 07:59 UTC
